### ISSUE TITLE
OneRel 解码问题

### ISSUE THREAD

**Issue by di-osc** [Xuanfang1121/relation_extract_OneRel_ch#2]
首先很感谢能分享中文的onerel实现, 但是我看解码部分代码的时候,发现好像不能对主体或者客体是一个token的情况解码,不知道是不是我的理解有误

**Comment by Xuanfang1121** [comment]
> 首先很感谢能分享中文的onerel实现, 但是我看解码部分代码的时候,发现好像不能对主体或者客体是一个token的情况解码,不知道是不是我的理解有误
主体和客体是不同实体，不能是同一个实体
